### ISSUE TITLE
[Bug]: Launch Crash

### ISSUE THREAD

**Issue by CodeRedFox** [TeamLapen/Werewolves#126] opened 2022-09-18 20:31 UTC
### Minecraft Version

1.18.2

### Forge Version

1.18.2-forge-40.1.0

### Vampirism Version

1.8.5

### Werewolves Version

1.8-0.6.2

### Singleplayer/Multiplayer

Singleplayer

### What happened?

Whenever I try to launch the game it always crashes while rendering overlay

### Relevant log output

```bash
java.lang.IncompatibleClassChangeError: class de.teamlapen.werewolves.client.model.geom.InvisibleModelPart cannot inherit from final class net.minecraft.client.model.geom.ModelPart
```

### Other relevant mods

Guide API VP
JEI
Waystones
WorldEdit

**Comment by Cheaterpaul** [comment] 2022-09-19 15:24
Duplicate of #96

**Comment by Cheaterpaul** [comment] 2022-09-19 15:25
send your log file

see https://wiki.werewolves.dev/docs/wiki/troubleshooting#javalangincompatibleclasschangeerrorfor more details

**Comment by CodeRedFox** [comment] 2022-09-22 01:31
The entire thing?

**Comment by CodeRedFox** [comment] 2022-09-22 01:35
I think I may have figured out the problem, I wasnt using the latest version of forge

**Comment by CodeRedFox** [comment] 2022-09-22 01:36
I'll get back to you if it doesnt work

**Comment by CodeRedFox** [comment] 2022-09-22 01:39
> send your log file
> 
> see https://wiki.werewolves.dev/docs/wiki/troubleshooting#javalangincompatibleclasschangeerrorfor more details

I worked! Thank you for the troubleshooting link. It fixed the problem :)

**Closed as completed** 2022-09-22 14:18 UTC
Labels: bug, unconfirmed
