### ISSUE TITLE
[Bug]: Ticking Entity

### ISSUE THREAD

**Issue by Mega4oSS** [TeamLapen/Werewolves#216] opened 2024-11-19 02:56 UTC
### Minecraft Version

1.19.x

### Forge Version

43.3.8

### Vampirism Version

1.9.5

### Werewolves Version

1.1.0.1

### Singleplayer/Multiplayer

Multiplayer

### What happened?

When Villager transformed to werewolve the crashes server (sorry idk how to descript it)
(But i suspect that the core is to blame)

Crash report:
[crash-2024-11-19_03.31.39-server.txt](https://github.com/user-attachments/files/17808641/crash-2024-11-19_03.31.39-server.txt)

### Relevant log output

```bash
Sorry, i can't insert log there because is too long. i Will place it behind, with a file.
```

**Comment by Cheaterpaul** [comment] 2024-12-08 14:15
Duplicate of #105

**Comment by Cheaterpaul** [comment] 2024-12-08 14:16
This seems to be an issue with arclight https://github.com/IzzelAliz/Arclight/issues/1227

**Closed as completed by Cheaterpaul** 2024-12-08 14:15 UTC
Labels: bug, unconfirmed

**Comment by Mega4oSS** [comment] 2024-12-09 08:57
Okay, thanks for info!
