### ISSUE TITLE
Werewolf Humans Spawn Uncontrollably In Spawn Chunks

### ISSUE THREAD

**Issue by polic72** [TeamLapen/Werewolves#49] opened 2021-06-19 05:03 UTC
## Versions
- Minecraft: 1.16.5
- Forge: 36.1.0
- Vampirism: Vampirism-1.16.4-1.7.12
- Werewolves: Werewolves-1.16.4-1.0.0-beta.1

- ModPack: Custom, Still happens with bare minimum mods.

## Issue Description
When spawning into a new world (only singleplayer tested), several thousand werewolf humans spawn underground over the course of a minute.

## Reproduce Steps
1. Create a singleplayer world.
2. Chill in spawn for a few minutes.
3. Go into spectator and see the several thousand werewolf humans underground.

## Additional Information
![2021-06-19_01 02 13](https://user-images.githubusercontent.com/28581221/122631487-1a512a80-d09a-11eb-9218-01f47bd29fdb.png)
![2021-06-19_01 02 27](https://user-images.githubusercontent.com/28581221/122631496-1f15de80-d09a-11eb-8ed1-3d7e8042b495.png)

**Comment by RazberryDream** [comment] 2021-06-20 06:13
Can confirm the spawn rate is insane in multiplayer servers _and_ in singleplayer, since I tested both. There were so many of these running around when I started the server with the mod freshly placed in.
![image](https://user-images.githubusercontent.com/83795584/122664066-a7f94c80-d164-11eb-8212-7c7abb74d858.png)

**Comment by Cheaterpaul** [comment] 2021-06-21 21:42
i can reproduce this. Will be fixed in the next version.

**Comment by Cheaterpaul** [comment] 2021-06-23 20:36
fixed by 920cf381283711e6503a1874dd4e092345a289c1 or ad8ddf8f2e4a221bf51a4fd5bffd9ab6c20098b7

**Closed as completed by Cheaterpaul** 2021-06-23 20:36 UTC
Labels: bug
