### ISSUE TITLE
[Bug]: Changed Register Key Crash - Vampirism Updated

### ISSUE THREAD

**Issue by KakashoLin** [TeamLapen/Werewolves#169] opened 2024-01-09 17:07 UTC
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Vampirism Version

Vampirism-1.20.1-1.10.3

### Werewolves Version

Werewolves-1.20.1-1.1.0.3

### Singleplayer/Multiplayer

Singleplayer

### What happened?

With the new Vampirisim update, the werewolves mod will crash the game. I am guessing values have been changed in newer updates.

 

"Unable to find registry with key vampirism:tasks for mod "werewolves"."

 

"java.lang.IllegalStateException: Unable to find registry with key vampirism:tasks for mod "werewolves"."

### Relevant log output

```bash
https://pastebin.com/MAgpxdde - Full Crash Report related to this issue.
```

### Reproduce steps

Update the Vampirism mod past the 10/15 version and the game will crash.

### Other relevant mods

Vampirism - Become a vampire!

**Comment by KakashoLin** [comment] 2024-01-09 17:15
Attaching related bug report from Vampirism: https://github.com/TeamLapen/Vampirism/issues/1319

**Comment by Cheaterpaul** [comment] 2024-01-09 21:20
Duplicate of #166

**Comment by Cheaterpaul** [comment] 2024-01-09 21:20
update werewolves to the latest beta

**Closed as completed by Cheaterpaul** 2024-01-09 21:20 UTC
Labels: bug, unconfirmed
