### ISSUE TITLE
[Bug]: tickrate spikes in certain areas with werewovles installed

### ISSUE THREAD

**Issue by EnderMelody** [TeamLapen/Werewolves#116] opened 2022-08-10 19:46 UTC
### Minecraft Version

1.18.x

### Forge Version

40.1.68

### Vampirism Version

1.8.5

### Werewolves Version

0.6.1

### Modpack

private pack

### Singleplayer/Multiplayer

Singleplayer

### What happened?

having werewolves installed causes high tick times every second in certain areas. the spikes are consistent and only appear with werewolves installed. These spikes only occur in certain areas, so im not sure what is causing it, possibly conflicting with another mod? reloading the world doesnt change anything, but reloading the the world without werewolves and then re-adding the mod seems to remove what causes the lag spikes.

seed used: -1217379669675027576
Worlds tps with werewolves: Spark: https://spark.lucko.me/NlKlZ51Cl6
![image](https://user-images.githubusercontent.com/12649140/183964690-c31c0ad2-328e-4202-b014-3e21f80b6f70.png)
Same worlds tps without werewolves: Spark: https://spark.lucko.me/GgTpEI0MEG
![image](https://user-images.githubusercontent.com/12649140/183982468-dc3cfd48-9ab1-4ef1-8a4f-e588b3f7f910.png)
Same worlds tps after loading the world without werewolves then adding it back in: Spark: https://spark.lucko.me/P1R8NbBzcQ
![image](https://user-images.githubusercontent.com/12649140/183961654-f74a8662-3f25-449e-ac74-ade50cecd823.png)

### Relevant log output

```bash
log with werewolves: [2022-08-10-with.log](https://github.com/TeamLapen/Werewolves/files/9302594/2022-08-10-with.log)
debug:[debug-with.log](https://github.com/TeamLapen/Werewolves/files/9302598/debug-with.log)

log without werewolves: [latest-without.log](https://github.com/TeamLapen/Werewolves/files/9302913/latest-without.log)
debug:[debug-without.log](https://github.com/TeamLapen/Werewolves/files/9302912/debug-without.log)

log after re-adding: [latest-readd.log](https://github.com/TeamLapen/Werewolves/files/9302918/latest-readd.log)
debug: [debug-readd.log](https://github.com/TeamLapen/Werewolves/files/9302917/debug-readd.log)
```

### Reproduce steps

1. load singleplayer world with the modpack.
2. depending on the area, you will see server tickrate lag spikes

**Comment by Cheaterpaul** [comment] 2022-08-10 20:56
Duplicate of #114

**Closed as completed by Cheaterpaul** 2022-08-10 20:56 UTC
Labels: bug, unconfirmed
